# Generated by Django 5.2.1 on 2025-10-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_details',
            field=models.JSONField(),
        ),
    ]
