# Generated by Django 5.2.1 on 2025-10-01 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('full_address', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('minimum_order_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('est_delivery_time', models.CharField(blank=True, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cuisines', models.ManyToManyField(blank=True, to='restaurants.cuisinetype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_orders', models.IntegerField(default=0)),
                ('today_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('today_average_rating', models.FloatField(default=3.0)),
                ('preparing', models.JSONField(default=list)),
                ('pending', models.JSONField(default=list)),
                ('completed', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='restaurants.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('prep_time', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('available', models.BooleanField(default=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'category'], name='restaurants_restaur_741f8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RestaurantExternalAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_apis', to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'category')},
            },
        ),
    ]
