# Generated by Django 5.2.1 on 2025-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='menuitem',
            name='restaurants_restaur_741f8f_idx',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'name'], name='restaurants_restaur_303786_idx'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(blank=True, to='restaurants.categorytype'),
        ),
    ]
