# Generated by Django 4.2.25 on 2025-10-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_categorytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(default='menu_items/placeholder.jpg', upload_to='menu_items/'),
        ),
    ]
