# Generated by Django 4.2.25 on 2025-10-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menuitem_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_profiles/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='item_image',
            field=models.ImageField(upload_to='menu_items/'),
        ),
    ]
