# Generated by Django 5.2.1 on 2025-10-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_lat_order_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lat',
            new_name='delivery_lat',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lng',
            new_name='delivery_lng',
        ),
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('delivery', 'delivery'), ('collection', 'collection')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
