# Generated by Django 4.2.25 on 2026-01-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_preparing_ready_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('preparing', 'preparing'), ('ready', 'ready'), ('collected', 'collected'), ('assigned', 'assigned'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='created', max_length=50),
        ),
    ]
