# Generated by Django 4.2.25 on 2026-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_collected_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'pending_payment'), ('paid', 'paid'), ('preparing', 'preparing'), ('ready', 'ready'), ('collected', 'collected'), ('assigned', 'assigned'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending_payment', max_length=50),
        ),
    ]
